"""Контстаты приложения foodgram."""
MAX_LENGTH_NAME = 256
MAX_LENGTH_SLUG = 50
MAX_LENGTH_USERNAME = 150
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_CODE = 40

USERNAME_REGEX = r'^[\w.@+-]+\Z'
SLUG_REGEX = r'^[-a-zA-Z0-9_]+$'

MIN_YEAR_VALUE = -3000
MIN_SCORE_VALUE = 1
MAX_SCORE_VALUE = 10

STR_SHORT_LENGTH = 20
STR_MEDIUM_LENGTH = 50

USER = 'user'
MODERATOR = 'moderator'
ADMIN = 'admin'

COOKING_TIME_MIN = 1
COOKING_TIME_MAX = 32000

RECIPE_INGREDIENT_AMOUT_MIN = 1
RECIPE_INGREDIENT_AMOUT_MAX = 32000

RANDOM_HASH_LENGTH_MIN = 15
RANDOM_HASH_LENGTH_MAX = 32

TAG_NAME_MAX_LENGTH = 23
INGREDIENT_NAME_MAX_LEENGTH = 128
RECIPE_NAME_MAX_LENGTH = 256

MAX_MEASUREMENT_INGREDIENT_UNIT = 64
USER_EMAIL_MAX_LENGTH = 254
USER_NAME_MAX_LENGTH = 150

ROLE_CHOICES = (
    (USER, 'Пользователь'),
    (MODERATOR, 'Модератор'),
    (ADMIN, 'Администратор'),
)
